local Crops = {
	Carrot = {
		Id = "Carrot",
		DisplayName = "Carrot",
		Rarity = "Common",
		SeedPrice = 8,
		BaseSell = 18,
		GrowthTime = 40,
		UnlockLevel = 1,
		Color = Color3.fromRGB(255, 140, 60),
		StageHeights = { 1.1, 2.2, 3.6, 5.4 },
	},
	Blueberry = {
		Id = "Blueberry",
		DisplayName = "Blueberry",
		Rarity = "Uncommon",
		SeedPrice = 16,
		BaseSell = 34,
		GrowthTime = 55,
		UnlockLevel = 2,
		Color = Color3.fromRGB(75, 110, 255),
		StageHeights = { 1.2, 2.6, 4.1, 5.8 },
	},
	Corn = {
		Id = "Corn",
		DisplayName = "Corn",
		Rarity = "Uncommon",
		SeedPrice = 26,
		BaseSell = 48,
		GrowthTime = 70,
		UnlockLevel = 4,
		Color = Color3.fromRGB(255, 216, 78),
		StageHeights = { 1.4, 3.1, 4.7, 6.5 },
	},
	CrystalBerry = {
		Id = "CrystalBerry",
		DisplayName = "Crystal Berry",
		Rarity = "Rare",
		SeedPrice = 44,
		BaseSell = 95,
		GrowthTime = 95,
		UnlockLevel = 6,
		Biome = "CrystalCave",
		Color = Color3.fromRGB(118, 255, 255),
		StageHeights = { 1.3, 2.8, 4.8, 6.7 },
	},
	EmberChili = {
		Id = "EmberChili",
		DisplayName = "Ember Chili",
		Rarity = "Rare",
		SeedPrice = 68,
		BaseSell = 145,
		GrowthTime = 110,
		UnlockLevel = 9,
		Biome = "Volcano",
		Color = Color3.fromRGB(255, 80, 60),
		StageHeights = { 1.5, 3.2, 5.4, 7.4 },
	},
	Starfruit = {
		Id = "Starfruit",
		DisplayName = "Sky Starfruit",
		Rarity = "Epic",
		SeedPrice = 120,
		BaseSell = 260,
		GrowthTime = 140,
		UnlockLevel = 14,
		Biome = "SkyIsland",
		Color = Color3.fromRGB(255, 242, 127),
		StageHeights = { 1.8, 3.5, 5.9, 8.2 },
	},
	MythicBean = {
		Id = "MythicBean",
		DisplayName = "Mythic Bean",
		Rarity = "Legendary",
		SeedPrice = 260,
		BaseSell = 520,
		GrowthTime = 180,
		UnlockLevel = 20,
		Biome = "SkyIsland",
		Color = Color3.fromRGB(185, 100, 255),
		StageHeights = { 2, 4, 6.7, 9.5 },
	},
}

return Crops
